// Authentication Related Actions
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';

// Data Storage Related Actions

export const STORE_MIN_COMPENSATION_DATA = 'STORE_MIN_COMPENSATION_DATA';
export const STORE_NOTES_COMPENSATION = 'STORE_NOTES_COMPENSATION';
export const STORE_NOTES_OPPORTUNITY = 'STORE_NOTES_OPPORTUNITY';
export const STORE_NOTES_JOBHUNT_REASON = 'STORE_NOTES_JOBHUNT_REASON';
export const STORE_SPECIALTIES_TAGS = 'STORE_SPECIALTIES_TAGS';
export const STORE_VISA_STATUS = 'STORE_VISA_STATUS'; // Is the Visa status an entity itself in Bullhorn or part of the comments?
export const STORE_NOTES_VISA_STATUS = 'STORE_NOTES_VISA_STATUS';
export const STORE_PAST_COMPANY_EXPERIENCE = 'STORE_PAST_COMPANY_EXPERIENCE'; // Should be a structured field, but is going to be unstructured for now and added in the comment section?
export const STORE_NOTES_LOCATION = 'STORE_NOTES_LOCATION';
export const STORE_NOTES_INTERVIEW_AVAILABILITY = 'STORE_NOTES_INTERVIEW_AVAILABILITY';
export const STORE_LOCATION = 'STORE_LOCATION';
export const STORE_NOTES_CURRENT_INTERVIEWS_ACTIVITY = 'STORE_NOTES_CURRENT_INTERVIEWS_ACTIVITY';
export const STORE_NOTES_START_DATE = 'STORE_NOTES_START_DATE';
